version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    image: registry.digitalocean.com/clutchbids-registry/p2p-listings:latest
    container_name: p2p-listings
    env_file:
      - .env